config/routes.rb
DealMeHealth::Application.routes.draw do
  
  get "pages/contact"

  get "pages/howitworks"

  get "pages/faq"

  get "pages/privacy"

  get "pages/termsofsale"

  get "pages/termsofuse"

  get "pages/partner"
  
  match '/contact',         :to => 'pages#contact'
  match '/howitworks',      :to => 'pages#howitworks'
  match '/faq',             :to => 'pages#faq'
  match '/privacy',         :to => 'pages#privacy'
  match '/termsofsale',     :to => 'pages#termsofsale'
  match '/termsofuse',      :to => 'pages#termsofuse'
  match '/partner',         :to => 'pages#partner'

  resources :coupons

  resources :deals

  resources :orders

  resources :locations

  devise_for :admins

  devise_for :users

  root :to => "deals#index"
  

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :deal
  belongs_to :customer
  has_many   :line_items
  has_many   :coupons
  
  def deals
  end
  
  def total_price
    line_items.to_a.sum(&:full_price)
  end
  
  def description
  end
  
  def paypal_url(return_url)
    values = {
      :business => 'seller_1229899173_biz@railscasts.com',
      :cmd => '_cart',
      :upload => 1,
      :return => return_url,
      :invoice => id
    }
    line_items.each_with_index do |item, index|
      values.merge!({
        "amount_#{index+1}" => item.unit_price,
        "item_name_#{index+1}" => item.deal.name,
        "item_number_#{index+1}" => item.id,
        "quantity_#{index+1}" => item.quantity
      })
    end
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
   before_filter :user_signed_in?
  # GET /orders
  # GET /orders.xml
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.xml
  def show
    @order = Order.find(params[:id])
	
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.xml
  def new
    @order = Order.new
	@order.user = current_user
	@order.deal = Deal.find(params[:deal_id])
	
	@coupon = Coupon.new
	
	
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
	

  end

  # POST /orders
  # POST /orders.xml
  def create
    @order = Order.new(params[:order])
	  @order.deal = Deal.find(params[:deal_id])	
	  @order.user = current_user
	
	  @coupon = Coupon.new(params[:coupon])

	
    respond_to do |format|
      if @order.save  &&  @coupon.save  && charge_the_card
        format.html { redirect_to(@order, :notice => 'Order was successfully created.') }
        format.xml  { render :xml => @order, :status => :created, :location => @order }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

   

  # PUT /orders/1
  # PUT /orders/1.xml
  def update
    @order = Order.find(params[:id])
	@order.deal = Deal.find(params[:deal_id])	
	@order.user = current_user

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to(@order, :notice => 'Order was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.xml
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to(orders_url) }
      format.xml  { head :ok }
    end
  end

  private
  
  def build_a_coupon(coupon)
	#todo Some of this logic would be happier in the coupon model
	#todo Currently we have a one model per form 
	
	@coupon.deal = @order.deal
	@coupon.token = current_user.username + current_user.created_at.to_s
	@coupon.total = @coupon.deal.price * @coupon.quantity
	@order.coupons << @coupon
  end 

  def charge_the_card	  
	  return true
  end 

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<% form_for @order,  :html => { :id=>"checkout", :class => "page_forms" }   do |f| %>
  <%= f.error_messages %> 
  <% fields_for(@coupon) do |coupon| %>
  <table>
	<tbody>
		<tr>
		  <th class="item_description">Item Description</th>
		  <th class="price">Price</th>
		  <th class="quantity">Quantity</th>
		  <th class="total">Total</th>
		</tr>
		<tr>
		  <td class="item_description"><%= @order.deal.description %></td>
		  <td class="price"><%= number_to_currency ( @order.deal.price) %> </td>
		  <td class="quantity"><%= coupon.text_field :quantity %></td>
		  <td class="total"><%= h @order.total_price %></td>
		</tr>
	  </tbody>
  </table>
  <% end %>
  <ul class="two_cols">
	<li>
	  <%= f.label :first_name %><br />
	  <div class="text_field_l">
		<div class="text_field_r">
		  <%= f.text_field :first_name %>
		</div>
	  </div>
	</li>
	<li>
		<%= f.label :card_number %><br />
	  <div class="text_field_l">
		<div class="text_field_r">
		  <%= f.text_field :card_number %>
		</div>
	  </div>
	</li>
  <li>
	<div class="cols monthyear">
	  <label>Expiration Date:</label>
		  <div>
			<select id="cardmonth" name="order[exp_month]">
			  <option value="">Month</option>
			  <option value="1">1</option>
			  <option value="2">2</option>
			  <option value="3">3</option>
			  <option value="4">4</option>
			  <option value="5">5</option>
			  <option value="6">6</option>
			  <option value="7">7</option>
			  <option value="8">8</option>
			  <option value="9">9</option>
			  <option value="10">10</option>
			  <option value="11">11</option>
			  <option value="12">12</option>
			</select>
		  </div>
		  <div>
			<select id="cardyear" name="order[exp_year]">
			  <option value="">Year</option>
			  <option value="2010">2010</option>
			  <option value="2011">2011</option>
			  <option value="2012">2012</option>
			  <option value="2013">2013</option>
			  <option value="2014">2014</option>
			  <option value="2015">2015</option>
			  <option value="2016">2016</option>
			  <option value="2017">2017</option>
			  <option value="2018">2018</option>
			  <option value="2019">2019</option>
			  <option value="2020">2020</option>
			  <option value="2021">2021</option>
			  <option value="2022">2022</option>
			  <option value="2023">2023</option>
			  <option value="2024">2024</option>
			  <option value="2025">2025</option>
			</select>
		  </div>
		</div>	
	  </li>
  <li class="cols cvv">
	<%= f.label :CVV %>
	<div class="text_field_l">
	  <div class="text_field_r">
		<%= f.text_field :security_code %>
	  </div>
	</div>
  </li>
</ul>
<ul class="two_cols">
  <li>
	<%= f.label :address_1 %><br />
	<div class="text_field_l">
	  <div class="text_field_r">
		  <%= f.text_field :address_1 %>
	  </div>
	</div>
  </li>
  <li>
	<%= f.label :address_2 %><br />
	<div class="text_field_l">
	  <div class="text_field_r">
		<%= f.text_field :address_2 %>
	  </div>
	</div>
  </li>  
  <li>
	<%= f.label :city %><br />
	<div class="text_field_l">
	  <div class="text_field_r">
		<%= f.text_field :city %>
	  </div>
	</div>
  </li>
  <li>
	<div class="cols state">
	<!-- a state select list with long names for keys and short names for display  -->
	
	<label>State</label>
	  <select id="order_credit_card_attributes_state" name="order[state]">
		<option value="">State</option>
		<option value="Alaska">AK</option>
		<option value="Alabama">AL</option>
		<option value="Arkansas">AR</option>
		<option value="Arizona">AZ</option>
		<option value="California">CA</option>
		<option value="Colorado">CO</option>
		<option value="Connecticut">CT</option>
		<option value="District of Columbia">DC</option>
		<option value="Delaware">DE</option>
		<option value="Florida">FL</option>
		<option value="Georgia">GA</option>
		<option value="Hawaii">HI</option>
		<option value="Iowa">IA</option>
		<option value="Idaho">ID</option>
		<option value="Illinois">IL</option>
		<option value="Indiana">IN</option>
		<option value="Kansas">KS</option>
		<option value="Kentucky">KY</option>
		<option value="Louisiana">LA</option>
		<option value="Massachusetts">MA</option>
		<option value="Maryland">MD</option>
		<option value="Maine">ME</option>
		<option value="Michigan">MI</option>
		<option value="Minnesota">MN</option>
		<option value="Missouri">MO</option>
		<option value="Mississippi">MS</option>
		<option value="Montana">MT</option>
		<option value="North Carolina">NC</option>
		<option value="North Dakota">ND</option>
		<option value="Nebraska">NE</option>
		<option value="New Hampshire">NH</option>
		<option value="New Jersey">NJ</option>
		<option value="New Mexico">NM</option>
		<option value="Nevada">NV</option>
		<option value="New York">NY</option>
		<option value="Ohio">OH</option>
		<option value="Oklahoma">OK</option>
		<option value="Oregon">OR</option>
		<option value="Pennsylvania">PA</option>
		<option value="Palau">PW</option>
		<option value="Rhode Island">RI</option>
		<option value="South Carolina">SC</option>
		<option value="South Dakota">SD</option>
		<option value="Tennessee">TN</option>
		<option value="Texas">TX</option>
		<option value="Utah">UT</option>
		<option value="Virginia">VA</option>
		<option value="Virgin Island">VI</option>
		<option value="Vermont">VT</option>
		<option value="Washington">WA</option>
		<option value="Wisconsin">WI</option>
		<option value="West Virginia">WV</option>
		<option value="Wyoming">WY</option>
	  </select>
	</div>
	<div class="cols zip">
	<label>ZIP</label>
	  <div class="text_field_l">
		<div class="text_field_r">
		  <%= f.text_field :zip_code %>
		</div>
	  </div>
	</div>
  </li>
  <li>
	<label>Phone</label>
	<div class="text_field_l">
		<div class="text_field_r">
		  <%= f.text_field :phone %>
		</div>
	  </div>	
  </li> 
   
</ul>  


<p>
  <%= link_to "Continue Shopping", deals_url %> |
  <%= link_to "Checkout", @order.paypal_url(deals_url) %>
</p>
<div id="order_is_processing"></div> 
<input type="hidden" name="deal_id"  value="<%= @order.deal.id %>" />
  
<% end %> <!-- end form_for order -->

app/views/orders/edit.html.erb
<%= render 'form' %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>    
    <th>First name &nbsp;</th>
    <th>Last name &nbsp;</th>
	<th>deal</th>
    <th colspan="3">Actions &nbsp;</th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    
    <td><%=h order.first_name %></td>
    <td><%=h order.last_name %></td>
	<td>
	  <ul>
	  <% order.coupons.each do |c| %>
	  	<li><%=h (c.deal.name + " " + number_to_currency(c.total_spent)) %></li>
	  <% end %>
	  </ul>
	</td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/orders/show.html.erb
<ul>
<% @order.coupons.each do |c| %>
<li><b>Deal: </b><%=h c.deal.name  %></li>
<li><b>Total: </b><%= number_to_currency(c.total_spent)%></li>
<% end %>
</ul>

<p>
  <b>First name:</b>
  <%=h @order.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%=h @order.last_name %>
</p>

<p>
  <b>Address1:</b>
  <%=h @order.address_1 %>
</p>

<p>
  <b>Address2:</b>
  <%=h @order.address_2 %>
</p>
<p>
  <b>City:</b>
  <%=h @order.city %>
</p>
<p>
  <b>State:</b>
  <%=h @order.state %>
</p>

<p>
  <b>Zip:</b>
  <%=h @order.zip_code %>
</p>

<p>
  <b>Phone:</b>
  <%=h @order.phone %>
</p>


<%=  link_to "Edit", :controller => "orders" , :action => "edit"%>
|
<%= link_to 'Back', orders_path %>