config/routes.rb
DealMeHealth::Application.routes.draw do
  
  get "pages/contact"

  get "pages/howitworks"

  get "pages/faq"

  get "pages/privacy"

  get "pages/termsofsale"

  get "pages/termsofuse"

  get "pages/partner"
  
  match '/contact',         :to => 'pages#contact'
  match '/howitworks',      :to => 'pages#howitworks'
  match '/faq',             :to => 'pages#faq'
  match '/privacy',         :to => 'pages#privacy'
  match '/termsofsale',     :to => 'pages#termsofsale'
  match '/termsofuse',      :to => 'pages#termsofuse'
  match '/partner',         :to => 'pages#partner'

  resources :coupons

  resources :deals

  resources :orders

  resources :locations

  devise_for :admins

  devise_for :users

  root :to => "deals#index"
  

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  has_many :orders
  belongs_to :location
  
  def price		
	return value - (value * (discount * 0.01))
  end 
  
  def off
    (((self.value-self.price)/self.value)*100).floor
  end
  
  def activated
    true if self.created_at
  end
  
  def savings
    self.value - self.price
  end
  
  def sold
    5
    #TODO: Implement
  end
  
  def remaining
    5
    #TODO: Implement
  end

  def max
    5
    #TODO: Implement
  end

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # GET /deals
  # GET /deals.xml
  def index
    @deals = Deal.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @deals }
    end
  end

  # GET /deals/1
  # GET /deals/1.xml
  def show
    @deal = Deal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.xml
  def new
    @deal = Deal.new
	
	if params[:location_id]
	  @location = Location.find(params[:location_id])
	end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.xml
  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to(@deal, :notice => 'Deal was successfully created.') }
        format.xml  { render :xml => @deal, :status => :created, :location => @deal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @deal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.xml
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to(@deal, :notice => 'Deal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @deal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.xml
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to(deals_url) }
      format.xml  { head :ok }
    end
  end

 
  
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :intro %><br />
    <%= f.text_field :intro %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :discount %><br />
    <%= f.text_field :discount %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.text_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<% form_for(@deal) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'form',  :locals => { :f => f } %>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<h1>Get em while they last</h1>

<table>
  <tr>
  </tr>

<% @deals.each do |deal| %>
  <tr>
	<td><%= h deal.name %><br/><%= h deal.photo %></td>
    <td><%= link_to 'Show', deal %></td>
    <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
    <td><%= link_to 'Destroy', deal, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New deal', new_deal_path %>

app/views/deals/new.html.erb
<h1>New deal</h1>

<% form_for(@deal) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'form',  :locals => { :f => f } %>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<script>
jQuery('.nav li:first').addClass('current');
</script>
<div class="mod-ext grid-580 bg-color0">
  <div class="mod-ext todays_scp scp_color2 txt2">
    <span class="scp_color1">Daily CheckUp:</span> <%= @deal.name %>
  </div>
  <div class="mod-ext the_deal">
    <div class="the_deal_snap">
      <img src="<%= @deal.photo %>" alt="<%= @deal.name %>" />
    </div>
    <div class="the_deal_info">
      <div class="mod center scp_color1 txt3">
        $<%= @deal.price %>
      </div>

<%=  link_to image_tag("/images/deals/buy_now.png") , :controller => "orders" , :action => "new", :deal_id => @deal %>
      <br />
      <div class="center">
        <ul class="value_info">
          <li>
            <%= @deal.off %>%<span>off</span>
          </li>

          <li>
            $<%= @deal.value %><span>value</span>
          </li>
          <li>
            $<%= @deal.savings %><span>savings</span>
          </li>
          <div class="clear"></div>
        </ul>
      </div>
      <div class="mod-ext center txt4 scp_color3"><span class="txt5">Hurry!</span> Time's a tickin'.</div>
      <div class="the_time">
        <div id="countdown" class="timer scp_bg_color4 rounded center txt5 color0"></div>
        <span class="txt6 center w-60">hours</span>
        <span class="txt6 center w-60">minutes</span>
        <span class="txt6 center w-60">seconds</span>
      </div>
    </div><!-- deal info ends here -->
    <div class="clear"></div>
    <div class="mod some_info">
      <br />
      <% if @deal.activated %>
        <% if @deal.max && @deal.sold >= (0.75 * @deal.max) %>
      <div id="progress_bar_wrapper" class="f-left">
        <div class="f-left txt8 status">Status: <span class="scp_color1 txt-trans-up">ACTIVE!</span></div>
        <div class="f-right sold scp_color2 txt4"><span class="txt2"><%= @deal.sold %></span> have been sold.</div>
        <div class="clear"></div>
        <div id="progress_bar">
          <div class="indicator step_2">bar</div>
        </div>
        <div class=" mod f-right scp_color2 txt8">
          Act Now - Only <span class="scp_color11"><%= (@deal.max - @deal.sold) %></span> available.
        </div>
      </div>
        <% else %>
      <div class="deal_on">
        <div class="scp_color2 purchases lh-55">
          <%= @deal.sold %> purchased.
        </div>
      </div>
        <% end %>
      <% else %>
      <div id="progress_bar_wrapper" class="f-left">
        <div class="f-left txt8 status">Status: <span class="scp_color11 txt-trans-up">Not yet active!</span></div>
        <div class="f-right sold scp_color2 txt4">
          <span class="txt2"><%= @deal.sold %></span> have been sold.
        </div>
        <div class="clear"></div>
        <div id="progress_bar">
          <div class="indicator step_1">bar</div>
        <% if @deal.min == 10 && @deal.sold <= 10 %>
          <div class="indicator step_2" style="width:<%= @deal.sold*5 %>px;position:absolute;top:0;left:0;">
            bar
          </div>
        <% elsif @deal.min == 5 && @deal.sold <= 5 %>
          <div class="indicator step_2" style="width:<%= @deal.sold*10 %>px;position:absolute;top:0;left:0;">
            bar
          </div>
        <% end %>
        </div>
        <div class="f-left activation scp_color13">
          <strong><%= @deal.remaining %></strong> to activate.
        </div>
        <div class="f-right"></div>
        <div class="clear"></div>
      </div>
      <% end %>


      <%#= render "tell_a_friend" %>

      <div class="clear"></div>
    </div><!-- deal's on ends here -->
  </div><!-- current deal ends here -->
</div><!-- inner container ends here -->

<%#= render "company_info" %>

<%= link_to 'Edit', edit_deal_path(@deal) %> <!-- | -->
<%= link_to 'Back', deals_path %>