config/routes.rb
DealMeHealth::Application.routes.draw do
  
  get "pages/contact"

  get "pages/howitworks"

  get "pages/faq"

  get "pages/privacy"

  get "pages/termsofsale"

  get "pages/termsofuse"

  get "pages/partner"
  
  match '/contact',         :to => 'pages#contact'
  match '/howitworks',      :to => 'pages#howitworks'
  match '/faq',             :to => 'pages#faq'
  match '/privacy',         :to => 'pages#privacy'
  match '/termsofsale',     :to => 'pages#termsofsale'
  match '/termsofuse',      :to => 'pages#termsofuse'
  match '/partner',         :to => 'pages#partner'

  resources :coupons

  resources :deals

  resources :orders

  resources :locations

  devise_for :admins

  devise_for :users

  root :to => "deals#index"
  

end

app/views/layouts/_footer.html.erb
<footer><div id="footercont">
  <nav class="round">
    <ul>
	  <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav></div>
</footer>

app/views/layouts/_header.html.erb
<header><div id="headercont">
    <%= image_tag("logo.png", :alt => "DealMeHealth", :class => "round") %>

	<div class="usernav">
		<% if user_signed_in? %>
			Welcome<b> <%= current_user.username %></b> Not you?
		<%= link_to 'Sign Out', destroy_user_session_path %>

		<% else %>
	<b>	<%= link_to 'Sign Up', new_user_registration_path %> </b>
		or 
		<%= link_to 'Sign In', new_user_session_path %>

		<% end %>
	<div class="clear"></div>

    <nav class="round">
      <ul>
		<li><%= link_to "Daily Check-Up", 	'#'               	%></li>
		<li><%= link_to "Recent Deals", 		deals_path      %></li>
		<li><%= link_to "How it works", 		howitworks_path %></li>
		<li><%= link_to "FAQs",         		faq_path   		%></li>
		<li><%= link_to "Contact Us",   		contact_path 	%></li>
       
      </ul>
    </nav>
		
</div>
  </header>

app/views/layouts/_sidebar.html.erb
    <div id="twtr-search-widget"></div>
      <script src="http://widgets.twimg.com/j/1/widget.js"></script>
      <link href="http://widgets.twimg.com/j/1/widget.css" type="text/css" rel="stylesheet">
      <script>
        new TWTR.Widget({
        search: '\"DealMeHealth\" OR @DealMeHealth', 
        id: 'twtr-search-widget',
        loop: true,
        title: 'What\'s being said about...',
        subject: 'Deal Me Health',
        width: 260,
        height: 300,
        theme: {
          shell: {
            background: '#e6e8e7',
            color: '#4f4f4f'
            },
          tweets: {
            background: '#ffffff',
            color: '#696969',
            links: '#f27d3a'
            }
          }
        }).render().start();
      </script>
    </div>


<div class="clear"></div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->    
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
  	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :defaults %>
  </head>
  <body>
		<%= render 'layouts/header' %>
			<div id="wrapper">

			  <!-- VIEW TEMPLATE Content DIV -->
			  <div id="content"><div class="clear"></div>
				<% flash.each do |key, value| %>
				  <div class="flash <%= key %>" > <%= value %></div>
				<% end %>
				<%= yield %>
			  </div>
			  <div class="sidebar">
				<div class="spiff">
				 <%= render 'layouts/sidebar' %>
				</div>
			  </div>
			</div>	 <div class="divClear"></div> 
	   		  <%= render 'layouts/footer' %>
  </body>

</html>

app/views/layouts/two_column.html.erb
<% content_for :content do %>
<div class="container_12">
  <div class="content_wrapper grid-640 f-left">
    <div class="content scp_bg-color3">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </div>
  <%= content_for?(:sidebar) ? yield(:sidebar) : render(:partial => "sidebar") %>
</div>
<% end %>
<%= render :file => 'layouts/application' %>